AWSTemplateFormatVersion: '2010-09-09'
Description: Cloud Services for Restaurant Inventory Manager

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod

Resources:
  InventoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Environment}-Inventory"
      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: ingredient
          AttributeType: S

      KeySchema:
        - AttributeName: ingredient
          KeyType: HASH

      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

      SSESpecification:
        SSEEnabled: true

      Tags:
        - Key: Service
          Value: InventoryManager

  MenuTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Environment}-Menu"
      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: menu_item
          AttributeType: S

      KeySchema:
        - AttributeName: menu_item
          KeyType: HASH

      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

      SSESpecification:
        SSEEnabled: true

      Tags:
        - Key: Service
          Value: InventoryManager

  SalesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Environment}-Sales"
      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: sale_id
          AttributeType: S

        - AttributeName: dayOfWeek
          AttributeType: S

        - AttributeName: date
          AttributeType: S

      KeySchema:
        - AttributeName: sale_id
          KeyType: HASH

      GlobalSecondaryIndexes:
        - IndexName: SalesByDayOfWeek
          KeySchema:
            - AttributeName: dayOfWeek
              KeyType: HASH
            - AttributeName: date
              KeyType: RANGE

          Projection:
            ProjectionType: ALL

      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

      SSESpecification:
        SSEEnabled: true

      Tags:
        - Key: Service
          Value: InventoryManager
  
  SupplyGapQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Environment}-supply-gap-queue"

      VisibilityTimeout: 30

      MessageRetentionPeriod: 345600 # 4 days

      ReceiveMessageWaitTimeSeconds: 20 # long polling

      Tags:
        - Key: Service
          Value: InventoryManager

  SupplyChangeQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Environment}-supply-change-queue"

      VisibilityTimeout: 30

      MessageRetentionPeriod: 345600 # 4 days

      ReceiveMessageWaitTimeSeconds: 20 # long polling

      Tags:
        - Key: Service
          Value: InventoryManager
  
  PriceReportTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${Environment}-price-report-topic"
      DisplayName: Price Report Alerts
      Tags:
        - Key: Service
          Value: InventoryManager

  PriceReportEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref PriceReportTopic
      Protocol: email
      Endpoint: eramming14@gmail.com


  AppEc2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}-restaurant-app-ec2-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: RestaurantAppAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: DynamoDbAccess
                Effect: Allow
                Action:
                  - dynamodb:*
                Resource:
                  - !GetAtt InventoryTable.Arn
                  - !GetAtt MenuTable.Arn
                  - !GetAtt SalesTable.Arn
                  - !Sub "${SalesTable.Arn}/index/*"

              - Sid: SqsAccess
                Effect: Allow
                Action:
                  - sqs:*
                Resource: 
                  - !GetAtt SupplyGapQueue.Arn
                  - !GetAtt SupplyChangeQueue.Arn

              - Sid: SnsAccess
                Effect: Allow
                Action:
                  - sns:*
                Resource: !Ref PriceReportTopic

              - Sid: GithubSshSecretsAccess
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:github-ssh-key*"

  AppEc2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub "${Environment}-restaurant-app-instance-profile"
      Roles:
        - !Ref AppEc2Role


Outputs:

  InventoryTableName:
    Description: Inventory table name
    Value: !Ref InventoryTable

  MenuTableName:
    Description: Menu table name
    Value: !Ref MenuTable

  SalesTableName:
    Description: Sales table name
    Value: !Ref SalesTable

  SalesByDayOfWeekIndex:
    Description: Sales forecasting GSI
    Value: SalesByDayOfWeek

  SupplyGapQueueUrl:
    Value: !Ref SupplyGapQueue

  SupplyGapQueueArn:
    Value: !GetAtt SupplyGapQueue.Arn

  SupplyChangeQueueUrl:
    Value: !Ref SupplyChangeQueue

  SupplyChangeQueueArn:
    Value: !GetAtt SupplyChangeQueue.Arn

  PriceReportTopicArn:
    Description: SNS topic ARN for price report notifications
    Value: !Ref PriceReportTopic
