AWSTemplateFormatVersion: '2010-09-09'
Description: Cloud Services for Restaurant Inventory Manager

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod

Resources:
  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and app traffic
      VpcId: vpc-0957698fb6be82426
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 # tighten this to your IP for real use

  InventoryManagerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-078f95be0757084a3
      InstanceType: t3.micro
      KeyName: EC2_SSH_Key
      IamInstanceProfile: !Ref AppEc2InstanceProfile
      SubnetId: subnet-0389b963c229d8bab
      SecurityGroupIds:
        - !Ref AppSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-InventoryManager"
        - Key: service
          Value: InventoryManager
        - Key: environment
          Value: !Ref Environment
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -euxo pipefail

          dnf update -y
          dnf install -y git awscli

          mkdir -p /root/.ssh
          aws secretsmanager get-secret-value \
            --secret-id github-ssh-key \
            --query SecretString \
            --output text > /root/.ssh/id_ed25519
          chmod 600 /root/.ssh/id_ed25519
          ssh-keyscan github.com >> /root/.ssh/known_hosts

          cat > /root/.ssh/config <<EOF
          Host github.com
            IdentityFile /root/.ssh/id_ed25519
            IdentitiesOnly yes
          EOF
          chmod 600 /root/.ssh/config
          git clone git@github.com:eramming/restaurant_manager.git /opt/restaurant_manager
          cd /opt/restaurant_manager
          echo "export AWS_REGION=us-east-2" >> /home/ec2-user/.bashrc
          echo "export AWS_DEFAULT_REGION=us-east-2" >> /home/ec2-user/.bashrc

  RecommendationEngineInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-078f95be0757084a3
      InstanceType: t3.micro
      KeyName: EC2_SSH_Key
      IamInstanceProfile: !Ref AppEc2InstanceProfile
      SubnetId: subnet-0389b963c229d8bab
      SecurityGroupIds:
        - !Ref AppSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-RecommendationEngine"
        - Key: service
          Value: RecommendationEngine
        - Key: environment
          Value: !Ref Environment
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -euxo pipefail

          dnf update -y
          dnf install -y git awscli

          mkdir -p /root/.ssh
          aws secretsmanager get-secret-value \
            --secret-id github-ssh-key \
            --query SecretString \
            --output text > /root/.ssh/id_ed25519
          chmod 600 /root/.ssh/id_ed25519
          ssh-keyscan github.com >> /root/.ssh/known_hosts

          cat > /root/.ssh/config <<EOF
          Host github.com
            IdentityFile /root/.ssh/id_ed25519
            IdentitiesOnly yes
          EOF
          chmod 600 /root/.ssh/config
          git clone git@github.com:eramming/restaurant_manager.git /opt/restaurant_manager
          cd /opt/restaurant_manager
          echo "export AWS_REGION=us-east-2" >> /home/ec2-user/.bashrc
          echo "export AWS_DEFAULT_REGION=us-east-2" >> /home/ec2-user/.bashrc

  PricingAnalyzerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-078f95be0757084a3
      InstanceType: t3.micro
      KeyName: EC2_SSH_Key
      IamInstanceProfile: !Ref AppEc2InstanceProfile
      SubnetId: subnet-0389b963c229d8bab
      SecurityGroupIds:
        - !Ref AppSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-PricingAnalyzer"
        - Key: service
          Value: PricingAnalyzer
        - Key: environment
          Value: !Ref Environment
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -euxo pipefail

          dnf update -y
          dnf install -y git awscli

          mkdir -p /root/.ssh
          aws secretsmanager get-secret-value \
            --secret-id github-ssh-key \
            --query SecretString \
            --output text > /root/.ssh/id_ed25519
          chmod 600 /root/.ssh/id_ed25519
          ssh-keyscan github.com >> /root/.ssh/known_hosts

          cat > /root/.ssh/config <<EOF
          Host github.com
            IdentityFile /root/.ssh/id_ed25519
            IdentitiesOnly yes
          EOF
          chmod 600 /root/.ssh/config
          git clone git@github.com:eramming/restaurant_manager.git /opt/restaurant_manager
          cd /opt/restaurant_manager
          echo "export AWS_REGION=us-east-2" >> /home/ec2-user/.bashrc
          echo "export AWS_DEFAULT_REGION=us-east-2" >> /home/ec2-user/.bashrc

  InventoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Environment}-Inventory"
      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: ingredient
          AttributeType: S

      KeySchema:
        - AttributeName: ingredient
          KeyType: HASH

      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

      SSESpecification:
        SSEEnabled: true

      Tags:
        - Key: Service
          Value: InventoryManager

  MenuTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Environment}-Menu"
      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: menu_item
          AttributeType: S

      KeySchema:
        - AttributeName: menu_item
          KeyType: HASH

      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

      SSESpecification:
        SSEEnabled: true

      Tags:
        - Key: Service
          Value: InventoryManager

  SalesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Environment}-Sales"
      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: sale_id
          AttributeType: S

        - AttributeName: dayOfWeek
          AttributeType: S

        - AttributeName: date
          AttributeType: S

      KeySchema:
        - AttributeName: sale_id
          KeyType: HASH

      GlobalSecondaryIndexes:
        - IndexName: SalesByDayOfWeek
          KeySchema:
            - AttributeName: dayOfWeek
              KeyType: HASH
            - AttributeName: date
              KeyType: RANGE

          Projection:
            ProjectionType: ALL

      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

      SSESpecification:
        SSEEnabled: true

      Tags:
        - Key: Service
          Value: InventoryManager
  
  ForecastQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Environment}-forecast-queue"

      VisibilityTimeout: 30

      MessageRetentionPeriod: 345600 # 4 days

      ReceiveMessageWaitTimeSeconds: 20 # long polling

      Tags:
        - Key: Service
          Value: InventoryManager
  
  PricingReportTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${Environment}-pricing-report-topic"
      DisplayName: Pricing Report Alerts
      Tags:
        - Key: Service
          Value: InventoryManager

  PricingReportEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref PricingReportTopic
      Protocol: email
      Endpoint: eramming14@gmail.com


  AppEc2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}-restaurant-app-ec2-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: RestaurantAppAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: DynamoDbAccess
                Effect: Allow
                Action:
                  - dynamodb:*
                Resource:
                  - !GetAtt InventoryTable.Arn
                  - !GetAtt MenuTable.Arn
                  - !GetAtt SalesTable.Arn
                  - !Sub "${SalesTable.Arn}/index/*"

              - Sid: SqsAccess
                Effect: Allow
                Action:
                  - sqs:*
                Resource: !GetAtt ForecastQueue.Arn

              - Sid: SnsAccess
                Effect: Allow
                Action:
                  - sns:*
                Resource: !Ref PricingReportTopic

              - Sid: GithubSshSecretsAccess
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:github-ssh-key*"

  AppEc2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub "${Environment}-restaurant-app-instance-profile"
      Roles:
        - !Ref AppEc2Role


Outputs:

  InventoryTableName:
    Description: Inventory table name
    Value: !Ref InventoryTable

  MenuTableName:
    Description: Menu table name
    Value: !Ref MenuTable

  SalesTableName:
    Description: Sales table name
    Value: !Ref SalesTable

  SalesByDayOfWeekIndex:
    Description: Sales forecasting GSI
    Value: SalesByDayOfWeek

  ForecastQueueUrl:
    Value: !Ref ForecastQueue

  ForecastQueueArn:
    Value: !GetAtt ForecastQueue.Arn

  PricingReportTopicArn:
    Description: SNS topic ARN for pricing report notifications
    Value: !Ref PricingReportTopic

  InventoryManagerPublicIP:
    Description: Public IP of InventoryManager instance
    Value: !GetAtt InventoryManagerInstance.PublicIp

  RecommendationEnginePublicIP:
    Description: Public IP of RecommendationEngine instance
    Value: !GetAtt RecommendationEngineInstance.PublicIp

  PricingAnalyzerPublicIP:
    Description: Public IP of PricingAnalyzer instance
    Value: !GetAtt PricingAnalyzerInstance.PublicIp

  InventoryManagerInstanceId:
    Description: Instance ID
    Value: !Ref InventoryManagerInstance

  RecommendationEngineInstanceId:
    Description: Instance ID
    Value: !Ref RecommendationEngineInstance

  PricingAnalyzerInstanceId:
    Description: Instance ID
    Value: !Ref PricingAnalyzerInstance